---
- name: Install required packages
  loop:
    - syncthing
    - syncthing-tools # fedora package claiming server tools, include just in case
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - syncthing

- name: Process user config
  loop: "{{ syncthing_general_users + syncthing_extra_users }}"
  loop_control:
    label: "{{ item.username }}"
  ansible.builtin.include_tasks: config.yml
  tags:
    - syncthing

...
