---
- name: Restart syncthing
  loop: "{{ syncthing_general_users + syncthing_extra_users }}"
  loop_control:
    label: "{{ item.username }}"
  ansible.builtin.systemd:
    name: "syncthing@{{ item.username }}"
    state: restarted
    daemon_reload: True

...
